stages:
  - Build

build:
  stage: Build
  script:
    - make build
  after_script:
    - make build-extract
  artifacts:
    when: always
    paths:
      - build
    expire_in: 3 days

npm-upload:
  stage: Build
  needs:
    - build
  script:
    - NPM_TOKEN=$NPM_TOKEN make npm-upload
  only:
    - main
